import classNames from "@/utilities/classnames";
import Image from "next/image";
import { FC, ReactNode } from "react";
import { FaCompass } from "react-icons/fa";
import { BsGithub, BsTwitter } from "react-icons/bs";
import { AiOutlineInstagram, AiFillLinkedin } from "react-icons/ai";
import { MdMail } from "react-icons/md";
import { FaFacebook } from "react-icons/fa";

export const metadata = {
  title: "Linktree",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="mt-8 flex h-full w-full items-center justify-center">
      <div className="grid w-full  gap-8 md:grid-cols-3">
        <Card
          href="https://yuvraj-links.vercel.app/"
          title="Website"
          desc="Go through v1 of linktree"
          className="bg-black dark:border md:dark:border-zinc-600 md:dark:border-zinc-800"
        >
          <FaCompass size={50} className="text-zinc-400" />
        </Card>
        <Card
          href="https://github.com/yuvrajdahal"
          title="Github"
          desc="@yuvrajdahal | Why not go through my projects 👀 "
          className="border bg-white"
        >
          <BsGithub size={50} />
        </Card>
        <Card
          href="https://www.instagram.com/yuvrajdl/"
          title="Instagram"
          desc="@yuvrajdl | 💻 DM to discover my digital portfolio!"
          className="bg-gradient-to-r from-pink-500 to-purple-500"
        >
          <AiOutlineInstagram className="text-white" size={50} />
        </Card>
        <Card
          href="https://twitter.com/yuvrajdl"
          title="Twitter"
          desc="@yuvrajdl | Feel free to follow"
          className="bg-blue-400"
        >
          <BsTwitter className="text-white" size={60} />
        </Card>
        <Card
          title="Facebook"
          href="https://www.facebook.com/Yuvraj.Srijal.Dahal"
          desc="Yuvraj dahal | Let's not talk about it"
          className="bg-blue-500"
        >
          <FaFacebook className="text-white" size={50} />
        </Card>
        <Card
          href="https://www.linkedin.com/in/yuvrajdahal"
          title="LinkedIn"
          desc="@yuvrajdahal | Let's connect!"
          className="bg-blue-500"
        >
          <AiFillLinkedin className="text-white" size={50} />
        </Card>
        <Card
          href="mailto:iamyuvraj456@gmail.com"
          title="Mail"
          desc="Exclusively for professional use."
          className="bg-gradient-to-r from-red-400 via-green-500 to-blue-500 saturate-150"
        >
          <MdMail className="text-white" size={50} />
        </Card>
      </div>
    </main>
  );
}
const Card: FC<{
  children?: ReactNode;
  title: string;
  desc: string;
  className?: string;
  href: string;
}> = ({ desc, href, title, className, children }) => {
  return (
    <div className="w-full rounded ">
      <div
        className={classNames(
          "h-[100px] w-full rounded shadow",
          "flex items-center justify-center",
          className
        )}
      >
        <div className="flex items-center justify-center">{children}</div>
      </div>
      <a href={href} target="_blank">
        <div className="mt-2 cursor-pointer text-dark hover:underline dark:text-light">
          {title}
        </div>
      </a>
      <div className="text-dark dark:text-zinc-700">{desc}</div>
    </div>
  );
};
